CROSSOVER_OPERATOR = "crossover"
MUTATION_OPERATOR = "mutation"

PROPORTIONAL_SELECTION = "proportional"
RANK_SELECTION = "rank"
TOURNAMENT_SELECTION = "tournament"
ELITIST_SELECTION = "elitist"
RANDOM_SELECTION = "random"

PARENTS_TO_SELECT = 1